"""Standalone V28 reports, cumulative append, provenance and final freeze."""
from __future__ import annotations
import argparse,json
from pathlib import Path
import numpy as np,pandas as pd
from jclosure.protocol_v28 import verify,verify_stage,stage_freeze
from jclosure.provenance import sha256_file,write_json_atomic
OUT=Path("results/v28/processed");R=Path("reports");SOURCE="src/jclosure/reporting_v28.py"
NAMES=["TOKEN_STATE_TRANSACTION_AUDIT_V28.md","NATURAL_WRITE_BOUNDARIES_V28.md","WRITE_FIDELITY_AUDIT_V28.md","NATURAL_WRITE_STATISTICS_V28.md","WRITE_INTERCEPTION_V28.md","WRITE_DOSE_RESPONSE_V28.md","READ_VS_WRITE_CAUSAL_MATRIX_V28.md","CHANNEL_WRITE_BLOCK_V28.md","CHANNEL_WRITE_FACTORIAL_V28.md","LAYERWISE_STATE_COMMIT_V28.md","NATURAL_WRITE_TRANSPLANT_V28.md","RECIPROCAL_WRITE_TRANSPLANT_V28.md","CURRENT_FUTURE_DISSOCIATION_V28.md","NEXT_WORKSPACE_DEPENDENCE_V28.md","STATE_COMMIT_HORIZON_V28.md","STRICT_INTERFACE_AUDIT_V28.md","EXECUTION_MANIFEST_V28.md","V28_SCIENTIFIC_ANSWERS_V28.md","V28_COMPLETE_REPORT.md"]
def load(root,n):return json.loads((root/OUT/n).read_text())
def w(root,n,s):(root/R/n).write_text(s.rstrip()+"\n",encoding="utf-8")
def num(x):return f"{x:.6f}"
def run(root,vtests,fulltests):
 base=verify(root);d=load(root,"design_v28.json");boundary=load(root,"transaction_boundary_audit_v28.json");amend=load(root,"endpoint_amendment_v28.json");dev=load(root,"development_analysis_v28.json");val=load(root,"validation_analysis_v28.json");adj=load(root,"v28_adjudication.json");fin=load(root,"final_confirmation_v28.json");td=load(root,"transplant_development_analysis_v28.json");tv=load(root,"transplant_validation_analysis_v28.json");matrix=pd.read_parquet(root/OUT/"read_write_causal_matrix_v28.parquet");fidelity=pd.read_parquet(root/OUT/"strict_write_fidelity_v28.parquet");writes=pd.read_parquet(root/OUT/"natural_write_statistics_v28.parquet");factor=pd.read_parquet(root/OUT/"channel_write_factorial_v28.parquet")
 w(root,NAMES[0],f"""# Token State Transaction Audit — V28

The Qwen3.5 hybrid text model has six linear-attention layers `{boundary['recurrent_layers']}` with REC and Conv state and two full-attention layers `{boundary['attention_layers']}` with KV state. The incoming cache after the prompt prefix is `P_t^in`; the model naturally computes the final prompt token and returns current layer-30 readout plus `P_t^out`. The next token consumes this returned cache.

The operative interception boundary is **after the complete token-t forward, before token t+1**. At this boundary natural outgoing fields already exist, current J/logits/semantic/workspace are captured and cannot be changed by later cache edits, and no current residual or output is overwritten. This is a temporal separation of an already-computed readout from a committed future condition; it is not proof of two independently implemented internal pathways.

The pilot found a historical naming ambiguity: layer-23 state-J is upstream of the tested writes, whereas the V26 h1 readout-J is layer 30. The formal V28 endpoint uses layer 30 at both t and t+1. The pilot development state `{amend['pilot_excluded_base_trial_id']}` was excluded from formal development; thresholds were unchanged. The amendment records that one pilot future response preceded endpoint freeze.
""")
 w(root,NAMES[1],"""# Natural Write Boundaries — V28

| field | incoming read in token t | natural outgoing update | current-token relation | valid post-forward interception |
|---|---|---|---|---|
| REC | GatedDeltaNet reads `recurrent_states` as initial state | gated delta rule computes and caches new recurrent state | mixer output is downstream of the recurrence; no claim that the update is current-invisible | exact old-state restoration |
| Conv | GatedDeltaNet reads `conv_states` for causal convolution | token update changes fixed-shape convolution context | current mixer consumes the convolution result | exact old-state restoration |
| KV | full attention reads old keys/values and includes token-t key/value | cache appends a new KV slot | current self-attention can consume the new slot | same-length new-slot replacement or same-length donor transplant |

Simply shortening KV to the previous cache length changes the next-token positional semantics. Therefore `KV_old_state_restore_valid = FALSE`; `KV_last_slot_previous_copy` is explicitly a native length-preserving diagnostic, **not** exact `P_out → P_in`.
""")
 w(root,NAMES[2],f"""# Write Fidelity Audit — V28

`{len(fidelity)}` native write-block, transplant, layer, wrong-write, and final interventions were audited; requested native tensors were written exactly, untouched fields were bitwise unchanged, current readout remained captured, and continuation token identity was unchanged in every row. Exact equality implies cosine 1 for nonzero copied fields, above the frozen 0.98 gate.

On 25 calibration states, clean replay h0 and same-state outgoing rewrite h1 were exactly zero. Development and validation clean h1 replay were also zero. The shuffled same-family full-state control changed h1 strongly (median Q `{load(root,'wrong_write_development_v28.json')['median_h1_q']:.6f}` development, `{load(root,'wrong_write_validation_v28.json')['median_h1_q']:.6f}` validation), demonstrating that arbitrary compatible state replacement is disruptive; it does not itself validate donor targeting. Norm-matched random write was not architecture-valid under the fixed native transaction and was not run.
""")
 statrows="\n".join(f"| {ch} | {len(x)} | {x.delta_norm.median():.6g} | {x.delta_norm.quantile(.25):.6g} | {x.delta_norm.quantile(.75):.6g} |" for ch,x in writes.groupby("channel"));w(root,NAMES[3],"# Natural Write Statistics — V28\n\nOn 25 calibration states, naturally generated outgoing fields were compared with their incoming fields. REC/Conv use direct tensor subtraction; KV uses the new slot minus the preceding slot, not a forced subtraction across unequal sequence lengths.\n\n| channel | layer-state rows | median write norm | Q1 | Q3 |\n|---|---:|---:|---:|---:|\n"+statrows+"\n\nThese are descriptive native-field statistics, not state dimensionality or causal potency estimates. A small-write versus large-write matched causal control was not adjudicated.\n")
 w(root,NAMES[4],f"""# Write Interception — V28

After an unmodified token-t forward, the predeclared primary interception restored the **exact incoming REC and Conv fields** into the naturally produced outgoing cache. Current layer-30 readout was never rewritten. Identical frozen next tokens were then processed.

| role | states | median h1 Q | potent fraction | max current Q |
|---|---:|---:|---:|---:|
| development | 74 | {dev['gates']['REC+Conv']['median_h1_q']:.6f} | {dev['gates']['REC+Conv']['potent_fraction']:.3f} | 0 |
| validation | 50 | {val['gates']['REC+Conv']['median_h1_q']:.6f} | {val['gates']['REC+Conv']['potent_fraction']:.3f} | 0 |
| independent final | 50 | {fin['median_h1_q']:.6f} | {fin['potent_fraction']:.3f} | 0 |

All five task families passed the frozen future-effect gate in all three panels. This establishes causal dependence of next-token readout on the naturally committed REC/Conv update under old-state restoration. The intervention is large and can be off the natural update manifold; dose and natural-donor controls constrain interpretation.
""")
 doses="\n".join(f"| {a} | {dev['dose_medians'][str(float(a))]:.6f} | {val['dose_medians'][str(float(a))]:.6f} |" for a in (0,.25,.5,.75,1));w(root,NAMES[5],"# Write Dose Response — V28\n\nFor fixed-shape REC/Conv, `P_in + α(P_out−P_in)` was written after natural token-t computation. h1 effect is measured against α=1 clean output.\n\n| retained write α | development median Q | validation median Q |\n|---:|---:|---:|\n"+doses+"\n\nBoth median curves decline monotonically. This is a finite dose relationship, not evidence of linearity, a compact state, or validity of KV interpolation.\n")
 matrixrows="\n".join(f"| {r.role} | {r.condition} | {r.read_current_median_q:.3f} | {r.read_future_median_q:.3f} | {r.write_current_median_q:.3f} | {r.write_future_median_q:.3f} |" for r in matrix.itertuples());w(root,NAMES[6],"# Read versus Write Causal Matrix — V28\n\nIncoming/read interventions act before token t; outgoing/write interventions act only after token t has completed. Effects are V26 h1-reference-normalized Q.\n\n| role | channel condition | read→Y_t | read→Y_t+1 | write→Y_t | write→Y_t+1 |\n|---|---|---:|---:|---:|---:|\n"+matrixrows+"\n\nThe phase asymmetry is experimentally validated for the tested conditions, but the zero current write effect is guaranteed by the chosen after-readout interception time.\n")
 channelrows="\n".join(f"| {c} | {dev['gates'][c]['median_h1_q']:.3f} | {val['gates'][c]['median_h1_q']:.3f} | {int(dev['gates'][c]['pass'])} | {int(val['gates'][c]['pass'])} |" for c in dev["gates"]);w(root,NAMES[7],"# Channel Write Block — V28\n\n| native condition | development median h1 Q | validation median h1 Q | dev gate | val gate |\n|---|---:|---:|---:|---:|\n"+channelrows+"\n\nREC and Conv exact old-state blocks each matter. KV new-slot replacement is a different, length-preserving intervention. All are current-preserving only because the post-forward readout is fixed. Marginal effect magnitude is not a channel ranking.\n")
 w(root,NAMES[8],f"""# Channel Write Factorial — V28

For the corrected native branch estimand, `I_REC,Conv = E_REC+Conv − E_REC − E_Conv` in the same recipient state and next token. Median `||I||/||E_REC+Conv||` is `{adj['factorial_interaction_over_joint_median']['development']:.6f}` development and `{adj['factorial_interaction_over_joint_median']['validation']:.6f}` validation. This non-additivity forbids summing marginal effects into a channel attribution. The V25 failed interaction estimand was not reused.
""")
 ldev=load(root,"layerwise_state_commit_development_v28.json");lval=load(root,"layerwise_state_commit_validation_v28.json");w(root,NAMES[9],f"""# Layerwise State Commit — V28

Exact per-layer REC/Conv old-state restoration and cumulative prefix/suffix restoration were run on 5 states per role. All `{ldev['rows']+lval['rows']}` interventions passed bitwise writeback. Largest single-layer median h1 Q was `{ldev['single_layer_max_median_q']:.6f}` development and `{lval['single_layer_max_median_q']:.6f}` validation; full cumulative medians were `{ldev['full_cumulative_median_q']:.6f}` and `{lval['full_cumulative_median_q']:.6f}`.

The scan is descriptive, not a pre-validated earliest causal layer or exclusive route; strong nonlinear effects permit multiple layers to have large marginals.
""")
 full=tv['profiles']['REC+Conv+KV_last_slot_previous_copy'];partial=tv['profiles']['REC+Conv'];w(root,NAMES[10],f"""# Natural Write Transplant — V28

Two independently computed natural branches per prompt were formed by a frozen incoming perturbation. The recipient current computation stayed untouched; donor outgoing native fields were inserted before the same next token. Full REC+Conv+KV replacement passed both directions in development and validation: median cosine ≈1, magnitude ratio 1, relative L2 to donor 0.

This complete-cache result is expected when the entire same-length future cache is made identical to the donor and the same token is replayed. It confirms fidelity and full-state transferability, **not** selective channel mediation or a compact state. REC+Conv partial transplant failed (validation A←B median cosine `{partial['directions']['A_from_B']['median_cosine']:.6f}`; B←A `{partial['directions']['B_from_A']['median_cosine']:.6f}`). Single-channel transplants also failed the reciprocal directional gate.
""")
 w(root,NAMES[11],"# Reciprocal Write Transplant — V28\n\nBoth `A ← B` and `B ← A` were executed for all same-prompt controlled pairs (10 development and 10 validation). Full outgoing-state transplant exactly reproduced the corresponding donor continuation in each direction; partial REC/Conv/KV combinations did not pass reciprocal gates. This reciprocal test distinguishes a complete compatible cache transfer from a one-direction anecdote. The full-cache identity remains a strong control rather than a localized mechanism.\n")
 w(root,NAMES[12],f"""# Current–Future Dissociation — V28

`V28-A = TRUE`: the natural REC+Conv outgoing update was blocked after current readout and before the next token, leaving current readout exactly captured while changing h1 by median `{dev['gates']['REC+Conv']['median_h1_q']:.6f}` development, `{val['gates']['REC+Conv']['median_h1_q']:.6f}` validation, and `{fin['median_h1_q']:.6f}` independent final. Incoming read interventions changed current output by median `{matrix[(matrix.role=='development')&(matrix.condition=='REC+Conv')].read_current_median_q.iloc[0]:.6f}` in development.

This is causal separation of present readout from the **committed future cache after readout**. It does not establish that write formation is causally independent of current readout during token-t computation, nor that current-silent hidden information pre-existed readout (V27-F remains).
""")
 jdev=matrix[(matrix.role=="development")&(matrix.condition=="REC+Conv")].write_j_future_median_q.iloc[0];jval=matrix[(matrix.role=="validation")&(matrix.condition=="REC+Conv")].write_j_future_median_q.iloc[0];w(root,NAMES[13],f"""# Next Workspace Dependence — V28

Restoring the natural outgoing REC+Conv write changed next-token layer-30 J by median `{jdev:.6f}` and `{jval:.6f}` reference scales in development and validation while current layer-30 J remained unchanged. Thus the next-token workspace/readout **depends causally on** the prior token's persistent-state commit under this intervention. The data do not show that the outgoing state fully constructs the workspace or is a compact sufficient state.
""")
 hdev=load(root,"state_commit_horizons_development_v28.json");hval=load(root,"state_commit_horizons_validation_v28.json");hrows="\n".join(f"| {h} | {hdev['median_q_by_horizon'][str(h)]:.6f} | {hval['median_q_by_horizon'][str(h)]:.6f} |" for h in (1,2,4));w(root,NAMES[14],"# State Commit Horizon — V28\n\nAfter h1 gates passed, 2 states per family were rolled out using identical clean-greedy continuation tokens in both branches.\n\n| horizon | development median Q | validation median Q |\n|---:|---:|---:|\n"+hrows+"\n\nThe write-block consequence attenuates but remains nonzero through h4. h8 was not opened.\n")
 w(root,NAMES[15],f"""# Strict Interface Audit — V28

- Parent commit: `{base['parent_commit']}`; protocol freeze: `{base['freeze_digest']}`.
- Disjoint panels: calibration 25, development 75 planned / 74 formal after explicit pilot exclusion, validation 50, independent final 50.
- Frozen boundary hash `{d['boundary_hash']}`; channel hash `{d['channel_hash']}`; intervention hash `{d['intervention_hash']}`; gate hash `{d['gate_hash']}`; final-opening hash `{d['final_opening_hash']}`.
- V27 historical result retained: `V27-F`; no historical final reopened.
- Endpoint amendment disclosed a pilot future response before layer-30 endpoint freeze; pilot state excluded from formal development and validation had not been opened.
- Full state transplant is an exact same-length cache identity control. KV old-state restoration is invalid; slot rewrite is diagnostic.
- Random norm-matched write, matched small/large-write effect control, and predictive `Y_t` versus `Y_t+write` comparison were not causally adjudicated; none enter formal gates.
- Independent final opened only after fixed REC+Conv development and validation gates.
- H3, dynamic state search, and autonomous controller remain unauthorized.
""")
 commands=["PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.protocol_v28 freeze","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.design_v28","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.transaction_v28 pilot","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.transaction_v28 plan","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.transaction_v28 audit","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.interventions_v28 amend","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.interventions_v28 development","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.analyze_v28 development","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.interventions_v28 validation","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.analyze_v28 validation","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.final_v28","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.transplant_v28 development","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.analyze_transplant_v28 development","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.transplant_v28 validation","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.analyze_transplant_v28 validation","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.secondary_v28 layerwise development","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.secondary_v28 layerwise validation","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.secondary_v28 horizons development","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.secondary_v28 horizons validation","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.wrong_write_v28 prepare","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.wrong_write_v28 development","CUDA_VISIBLE_DEVICES=0 PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.wrong_write_v28 validation","PYTHONPATH=src /home/user/anaconda3/bin/python -m jclosure.experiments.adjudicate_v28","PYTHONPATH=src /home/user/anaconda3/bin/python -m pytest tests/test_v28_token_state_transaction.py -q","PYTHONPATH=src /home/user/anaconda3/bin/python -m pytest -q","git commit -m 'Complete V28 token state transaction study'","git push origin main"]
 manifest={"commands":commands,"v28_tests":vtests,"full_suite":fulltests,"formal_outcomes":adj["formal_outcomes"],"historical_final_opened":False,"v28_independent_final_opened":True};write_json_atomic(root/OUT/"execution_manifest_v28.json",manifest);w(root,NAMES[16],"# Execution Manifest — V28\n\n"+"\n".join(f"- `{c}`" for c in commands)+f"\n\nV28 tests: `{vtests}`. Full suite: `{fulltests}`. The three failures are inherited V14/V16/V25 cumulative `FINAL_REPORT.md` hash checks.\n")
 answers=["The incoming state is the prefix cache: per-layer REC and Conv tensors plus attention KV sequences.","The outgoing state is the same native cache after natural processing of token t, with updated REC/Conv and appended KV.","REC and Conv are read in the linear-attention mixer; KV is read by full attention.","REC/Conv update during token-t mixer execution; KV appends during attention.","The returned cache commits after the complete token-t forward.","The current mixer can depend on state updates; post-forward interception occurs after current layer-30 readout is fixed.","Yes, at the post-forward, pre-next-token cache boundary.","Yes, current readout remains exactly captured (Q=0).","Yes, REC+Conv old-state restoration changes h1 median Q 34.55 development and 36.82 validation.","The independent final median h1 Q is 35.87; all 50 states exceed 0.25.","Yes, REC+Conv retained-write dose medians decrease monotonically from α=0 to 1.","Yes, REC exact write block changes h1 in all families.","Yes, Conv exact write block changes h1 in all families.","KV previous-slot rewrite changes h1, but it is not exact old-state restoration.","REC+Conv and the length-preserving all-channel condition change h1; additivity fails.","Per-layer effects are substantial; no unique earliest commit layer is established.","Yes, incoming interventions materially affect current output.","Yes, outgoing interception selectively changes future output because current output is already fixed.","Yes, at the chosen temporal boundary; this does not establish internal path independence during token-t execution.","Yes, full same-length natural outgoing cache was transplanted.","Yes, full-cache transplant exactly reaches donor continuation; partial channels fail reciprocal directional gates.","Yes, next-token layer-30 J changes strongly under REC+Conv write block.","Yes, h2 and h4 effects remain nonzero but attenuate.","Yes, current readout and committed outgoing state are causally separable after current computation.","Yes, V28-A is supported.","Yes, V28-B is supported under exact REC+Conv old-state restoration.","V28-C is supported for full-cache identity transfer; V28-D/E are not formally supported.","Yes, H2 remains.","No, H3 remains unauthorized.","Yes for the tested temporal transaction: V26/V27 are better reconciled by read-now/write-for-next than by a pre-existing current-silent state, without a compact-state claim."]
 write_json_atomic(root/OUT/"v28_scientific_answers.json",{"answers":answers});w(root,NAMES[17],"# V28 Scientific Answers\n\n"+"\n".join(f"{i}. {x}" for i,x in enumerate(answers,1)))
 complete=f"""# V28 Complete Report

## Identity and frozen starting point

**Token-Level Persistent State Read/Write Transaction**. Parent `{base['parent_commit']}`; protocol `{base['freeze_digest']}`; boundary `{d['boundary_hash']}`; adjudication `{adj['ADJUDICATION_HASH']}`. V27-F remains the starting point: V26's current silence was post-readout, whereas tested pre-readout perturbations changed current output. V28 does not revive pre-existing current-silent memory, compact state, or H3.

## Architecture and prospective design

In Qwen3.5, six layers have native REC/Conv state and two have attention KV. After the complete natural token-t forward, layer-30 current readout and outgoing cache are both available. Exact incoming REC/Conv fields can replace the natural outgoing fields without touching current activations; KV cannot be shortened to the old sequence length without changing positional semantics, so its new-slot copy is a separately labeled diagnostic. All future branches use identical next tokens.

Disjoint balanced panels were frozen at 25 calibration, 75 development, 50 validation, and 50 independent-final states. One development pilot state was explicitly removed from formal analysis after the layer-23 versus layer-30 J naming ambiguity was discovered; primary results use 74 development states and layer-30 readout-J at both t and t+1. The pilot future observation and unchanged thresholds are recorded in an append-only endpoint amendment.

## Formal outcomes

`V28-A=TRUE`, `V28-B=TRUE`, `V28-C=TRUE`, `V28-D=FALSE`, `V28-E=FALSE`, `V28-F=FALSE`, `V28-G=FALSE`, `V28-H=FALSE`.

The predeclared **exact REC+Conv natural-write block** left the already-computed current readout unchanged (Q=0) while altering next-token readout by median Q `{dev['gates']['REC+Conv']['median_h1_q']:.6f}` development, `{val['gates']['REC+Conv']['median_h1_q']:.6f}` validation, and `{fin['median_h1_q']:.6f}` independent final. All five families replicated, all formal writebacks were exact, and the potent fraction was 1.0 in each panel. Incoming-state read interventions, by contrast, changed current output. Natural-write dose effects declined monotonically as the retained REC/Conv update approached 100%.

Natural same-prompt donor branches showed exact **full outgoing-cache** transfer under both reciprocal directions, with cosine ≈1 and magnitude ratio 1. This is a complete-cache identity control: making the future cache equal to a donor and replaying the same token should reproduce that donor. It establishes full-state transplant fidelity/transferability but does **not** identify a selective single-channel route. Single REC, Conv, KV, and REC+Conv partial transplants did not pass the reciprocal donor-direction gate. Individual write blocks nevertheless had large marginal effects, so neither a purely distributed-only necessity claim nor a global channel ranking is justified.

## Workspace and horizons

Next-token layer-30 J changes under write block by median Q `{jdev:.6f}` development and `{jval:.6f}` validation despite fixed current J. This supports that next workspace depends causally on the prior outgoing REC/Conv commit, not that it is fully constructed by or identical to a compact state. h1/h2/h4 median Q is `{hdev['median_q_by_horizon']['1']:.3f}/{hdev['median_q_by_horizon']['2']:.3f}/{hdev['median_q_by_horizon']['4']:.3f}` development and `{hval['median_q_by_horizon']['1']:.3f}/{hval['median_q_by_horizon']['2']:.3f}/{hval['median_q_by_horizon']['4']:.3f}` validation.

## Limits and interpretation

The zero current write effect is guaranteed by the after-readout interception boundary; the nontrivial causal result is that blocking **the natural outgoing update**, rather than adding an arbitrary future perturbation, changes subsequent computation and survives dose/replication/final tests. Old-state restoration can be off-manifold; same-family shuffled full cache also causes large future changes. Exact full-cache transfer is expected, and partial transfer failure prevents a localized-carrier claim. Predictive write features, norm-matched random write, and a matched small-write causal control were not established and are excluded from formal gates. No compact or complete-state inference is made.

`H2_REMAINS=TRUE`; `H3_AUTHORIZED=FALSE`; `DYNAMIC_STATE_SEARCH_AUTHORIZED=FALSE`; `AUTONOMOUS_CONTROLLER_AUTHORIZED=FALSE`.

V28 tests: `{vtests}`. Full suite: `{fulltests}`; three inherited cumulative-report hash checks fail.
"""
 w(root,NAMES[18],complete);final=root/R/"FINAL_REPORT.md"
 if "# V28 Complete Report" in final.read_text(encoding="utf-8"):raise RuntimeError("V28 already appended")
 final.write_text(final.read_text(encoding="utf-8").rstrip()+"\n\n---\n\n"+complete.rstrip()+"\n",encoding="utf-8");write_json_atomic(root/OUT/"v28_test_audit.json",{"v28_tests":vtests,"full_suite":fulltests,"inherited_failures":["V14 cumulative FINAL_REPORT hash","V16 cumulative FINAL_REPORT hash","V25 cumulative FINAL_REPORT hash"]})
 paths=[]
 for directory in ("artifacts","results/v28/processed","reports"):
  for p in sorted((root/directory).glob("**/*")):
   rel=str(p.relative_to(root))
   if p.is_file() and ("v28" in rel.lower() or rel=="reports/FINAL_REPORT.md") and not rel.endswith("v28_integrity_index.json"):paths.append(rel)
 integrity={"files":{p:sha256_file(root/p) for p in paths},"file_count":len(paths),"protocol_hash":base["freeze_digest"],"state_hashes":d["state_hashes"],"token_hash_source":"transaction_boundary_audit_v28.parquet and all intervention rows","incoming_outgoing_hash_source":"transaction_boundary_audit_v28.parquet","write_boundary_hash":d["boundary_hash"],"channel_hash":d["channel_hash"],"transplant_hashes":{r:load(root,f"natural_write_transplant_{r}_v28.json")["response_sha256"] for r in ("development","validation")},"intervention_hash":d["intervention_hash"],"adjudication_hash":adj["ADJUDICATION_HASH"],"final_opening_hash":load(root,"final_opening_v28.json")["final_opening_hash"],"historical_final_opened":False,"v28_independent_final_opened":True};ip=root/OUT/"v28_integrity_index.json";write_json_atomic(ip,integrity)
 inputs=[SOURCE,"tests/test_v28_token_state_transaction.py",str(ip.relative_to(root)),"results/v28/processed/v28_adjudication.json","results/v28/processed/execution_manifest_v28.json","results/v28/processed/v28_scientific_answers.json","reports/FINAL_REPORT.md"]+[f"reports/{n}" for n in NAMES]
 fr=stage_freeze(root,"final",inputs,{"formal_outcomes":adj["formal_outcomes"],"integrity_index_sha256":sha256_file(ip),"reports":len(NAMES),"historical_final_opened":False,"v28_independent_final_opened":True,"H3_AUTHORIZED":False,"DYNAMIC_STATE_SEARCH_AUTHORIZED":False,"AUTONOMOUS_CONTROLLER_AUTHORIZED":False});return {"final_freeze_digest":fr["freeze_digest"],"reports":len(NAMES),"integrity_files":len(paths),"formal_outcomes":adj["formal_outcomes"]}
if __name__=="__main__":
 p=argparse.ArgumentParser();p.add_argument("--v28-tests",required=True);p.add_argument("--full-tests",required=True);a=p.parse_args();print(json.dumps(run(Path.cwd(),a.v28_tests,a.full_tests),indent=2))
